### ISSUE TITLE
Unexpected changing IDE windows

### ISSUE THREAD

**Issue by rjhornsby** [burliayeu/IDEA-Native-Terminal-Plugin#30]
I'm honestly not sure if this is an issue with Native Terminal or with the JB IDE framework, but thought I would start here. Using Native Terminal 0.4.1, RM 2019.2.1.

When I have more than one JB IDE (ie Rubymine) window open, and I use the keyboard shortcut (cmd+`) to tell Native Terminal to open an iTerm2 window, very often the order of which IDE window is on top will change. For example, say I have two projects, A and B, open in Rubymine in separate windows, but one on top of the other. I have project A on top/in focus, and I hit my keyboard shortcut, a terminal window opens properly (side note: this plugin is amazing and useful), but suddenly the window for project B is on top of project A.

It's very confusing because when I click from the terminal window back to the IDE, it's the wrong project. It's very much a "this code doesn't look right..." for a bit until I realize the window order has changed and I'm not looking at the project I thought I was.

This scenario is true for at least Rubymine and Pycharm. Preferences > Keymap only shows this shortcut bound to Native Terminal. The only setting for the plugin is the Terminal, which is set to `/Applications/iTerm.app`.

**Comment by sburlyaev** [comment]
Hi @rjhornsby,

Have you tried another shortcut? Looks like `Command+`\` is macOS' native "Cycles through windows" command.

Thank you!
